// Auto generated by Craby. DO NOT EDIT.
#include "CxxCryptoAtomicsKeyModule.hpp"
#include "cxx.h"
#include "bridging-generated.hpp"
#include <react/bridging/Bridging.h>

using namespace facebook;

namespace craby {
namespace cryptoatomicskey {
namespace modules {

std::string CxxCryptoAtomicsKeyModule::dataPath = std::string();

CxxCryptoAtomicsKeyModule::CxxCryptoAtomicsKeyModule(
    std::shared_ptr<react::CallInvoker> jsInvoker)
    : TurboModule(CxxCryptoAtomicsKeyModule::kModuleName, jsInvoker) {
  // No signals
  callInvoker_ = std::move(jsInvoker);
  module_ = std::shared_ptr<craby::cryptoatomicskey::bridging::CryptoAtomicsKey>(
    craby::cryptoatomicskey::bridging::createCryptoAtomicsKey(
      reinterpret_cast<uintptr_t>(this),
      rust::Str(dataPath.data(), dataPath.size())).into_raw(),
    [](craby::cryptoatomicskey::bridging::CryptoAtomicsKey *ptr) { rust::Box<craby::cryptoatomicskey::bridging::CryptoAtomicsKey>::from_raw(ptr); }
  );
  threadPool_ = std::make_shared<craby::cryptoatomicskey::utils::ThreadPool>(10);
  methodMap_["generateAndStore"] = MethodMetadata{2, &CxxCryptoAtomicsKeyModule::generateAndStore};
  methodMap_["getActiveKeyHex"] = MethodMetadata{0, &CxxCryptoAtomicsKeyModule::getActiveKeyHex};
  methodMap_["getDerivationProgress"] = MethodMetadata{0, &CxxCryptoAtomicsKeyModule::getDerivationProgress};
  methodMap_["setCredentials"] = MethodMetadata{2, &CxxCryptoAtomicsKeyModule::setCredentials};
  methodMap_["signMessage"] = MethodMetadata{1, &CxxCryptoAtomicsKeyModule::signMessage};
  methodMap_["unlock_and_get_key"] = MethodMetadata{2, &CxxCryptoAtomicsKeyModule::unlockAndGetKey};
}

CxxCryptoAtomicsKeyModule::~CxxCryptoAtomicsKeyModule() {
  invalidate();
}

void CxxCryptoAtomicsKeyModule::invalidate() {
  if (invalidated_.exchange(true)) {
    return;
  }

  invalidated_.store(true);
  listenersMap_.clear();

  // No signals

  // Shutdown thread pool
  threadPool_->shutdown();
}

jsi::Value CxxCryptoAtomicsKeyModule::generateAndStore(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCryptoAtomicsKeyModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    craby::cryptoatomicskey::bridging::generateAndStore(*it_, arg0, arg1);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cryptoatomicskey::utils::errorMessage(err));
  }
}

jsi::Value CxxCryptoAtomicsKeyModule::getActiveKeyHex(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCryptoAtomicsKeyModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::cryptoatomicskey::bridging::getActiveKeyHex(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cryptoatomicskey::utils::errorMessage(err));
  }
}

jsi::Value CxxCryptoAtomicsKeyModule::getDerivationProgress(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCryptoAtomicsKeyModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (0 != count) {
      throw jsi::JSError(rt, "Expected 0 argument");
    }

    auto ret = craby::cryptoatomicskey::bridging::getDerivationProgress(*it_);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cryptoatomicskey::utils::errorMessage(err));
  }
}

jsi::Value CxxCryptoAtomicsKeyModule::setCredentials(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCryptoAtomicsKeyModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    craby::cryptoatomicskey::bridging::setCredentials(*it_, arg0, arg1);

    return jsi::Value::undefined();
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cryptoatomicskey::utils::errorMessage(err));
  }
}

jsi::Value CxxCryptoAtomicsKeyModule::signMessage(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCryptoAtomicsKeyModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (1 != count) {
      throw jsi::JSError(rt, "Expected 1 argument");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto ret = craby::cryptoatomicskey::bridging::signMessage(*it_, arg0);

    return react::bridging::toJs(rt, ret);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cryptoatomicskey::utils::errorMessage(err));
  }
}

jsi::Value CxxCryptoAtomicsKeyModule::unlockAndGetKey(jsi::Runtime &rt,
                                react::TurboModule &turboModule,
                                const jsi::Value args[],
                                size_t count) {
  auto &thisModule = static_cast<CxxCryptoAtomicsKeyModule &>(turboModule);
  auto callInvoker = thisModule.callInvoker_;
  auto it_ = thisModule.module_;

  try {
    if (2 != count) {
      throw jsi::JSError(rt, "Expected 2 arguments");
    }

    auto arg0$raw = args[0].asString(rt).utf8(rt);
    auto arg0 = rust::Str(arg0$raw.data(), arg0$raw.size());
    auto arg1$raw = args[1].asString(rt).utf8(rt);
    auto arg1 = rust::Str(arg1$raw.data(), arg1$raw.size());
    react::AsyncPromise<rust::String> promise(rt, callInvoker);

    thisModule.threadPool_->enqueue([it_, promise, arg0, arg1]() mutable {
      try {
        auto ret = craby::cryptoatomicskey::bridging::unlockAndGetKey(*it_, arg0, arg1);
        promise.resolve(ret);
      } catch (const jsi::JSError &err) {
        promise.reject(err.getMessage());
      } catch (const std::exception &err) {
        promise.reject(craby::cryptoatomicskey::utils::errorMessage(err));
      }
    });

    return react::bridging::toJs(rt, promise);
  } catch (const jsi::JSError &err) {
    throw err;
  } catch (const std::exception &err) {
    throw jsi::JSError(rt, craby::cryptoatomicskey::utils::errorMessage(err));
  }
}

} // namespace modules
} // namespace cryptoatomicskey
} // namespace craby
