// Auto generated by Craby. DO NOT EDIT.
#pragma once

#include "CrabyUtils.hpp"
#include "ffi.rs.h"
#include <ReactCommon/TurboModule.h>
#include <jsi/jsi.h>
#include <memory>

namespace craby {
namespace cryptoatomicskey {
namespace modules {

class JSI_EXPORT CxxCryptoAtomicsKeyModule : public facebook::react::TurboModule {
public:
  static constexpr const char *kModuleName = "CryptoAtomicsKey";
  static std::string dataPath;

  CxxCryptoAtomicsKeyModule(std::shared_ptr<facebook::react::CallInvoker> jsInvoker);
  ~CxxCryptoAtomicsKeyModule();

  void invalidate();
  static facebook::jsi::Value
  generateAndStore(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  getActiveKeyHex(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  getDerivationProgress(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  setCredentials(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  signMessage(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

  static facebook::jsi::Value
  unlockAndGetKey(facebook::jsi::Runtime &rt,
      facebook::react::TurboModule &turboModule,
      const facebook::jsi::Value args[], size_t count);

protected:
  std::shared_ptr<facebook::react::CallInvoker> callInvoker_;
  std::shared_ptr<craby::cryptoatomicskey::bridging::CryptoAtomicsKey> module_;
  std::atomic<bool> invalidated_{false};
  std::atomic<size_t> nextListenerId_{0};
  std::mutex listenersMutex_;
  std::unordered_map<
    std::string,
    std::unordered_map<size_t, std::shared_ptr<facebook::jsi::Function>>>
    listenersMap_;
  std::shared_ptr<craby::cryptoatomicskey::utils::ThreadPool> threadPool_;
};

} // namespace modules
} // namespace cryptoatomicskey
} // namespace craby
