// Auto generated by Craby. DO NOT EDIT.
#[rustfmt::skip]
use craby::prelude::*;

use crate::crypto_atomics_key_impl::*;
use crate::generated::*;

use bridging::*;

#[cxx::bridge(namespace = "craby::cryptoatomicskey::bridging")]
pub mod bridging {
    extern "Rust" {
        type CryptoAtomicsKey;

        #[cxx_name = "createCryptoAtomicsKey"]
        fn create_crypto_atomics_key(id: usize, data_path: &str) -> Box<CryptoAtomicsKey>;

        #[cxx_name = "generateAndStore"]
        fn crypto_atomics_key_generate_and_store(it_: &mut CryptoAtomicsKey, password: &str, db_path: &str) -> Result<()>;

        #[cxx_name = "getActiveKeyHex"]
        fn crypto_atomics_key_get_active_key_hex(it_: &mut CryptoAtomicsKey) -> Result<String>;

        #[cxx_name = "getDerivationProgress"]
        fn crypto_atomics_key_get_derivation_progress(it_: &mut CryptoAtomicsKey) -> Result<f64>;

        #[cxx_name = "setCredentials"]
        fn crypto_atomics_key_set_credentials(it_: &mut CryptoAtomicsKey, password: &str, db_path: &str) -> Result<()>;

        #[cxx_name = "signMessage"]
        fn crypto_atomics_key_sign_message(it_: &mut CryptoAtomicsKey, message: &str) -> Result<String>;

        #[cxx_name = "unlockAndGetKey"]
        fn crypto_atomics_key_unlock_and_get_key(it_: &mut CryptoAtomicsKey, password: &str, db_path: &str) -> Result<String>;
    }
}

fn create_crypto_atomics_key(id: usize, data_path: &str) -> Box<CryptoAtomicsKey> {
    let ctx = Context::new(id, data_path);
    Box::new(CryptoAtomicsKey::new(ctx))
}

fn crypto_atomics_key_generate_and_store(it_: &mut CryptoAtomicsKey, password: &str, db_path: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.generate_and_store(password, db_path);
        ret
    })
}

fn crypto_atomics_key_get_active_key_hex(it_: &mut CryptoAtomicsKey) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.get_active_key_hex();
        ret
    })
}

fn crypto_atomics_key_get_derivation_progress(it_: &mut CryptoAtomicsKey) -> Result<f64, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.get_derivation_progress();
        ret
    })
}

fn crypto_atomics_key_set_credentials(it_: &mut CryptoAtomicsKey, password: &str, db_path: &str) -> Result<(), anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.set_credentials(password, db_path);
        ret
    })
}

fn crypto_atomics_key_sign_message(it_: &mut CryptoAtomicsKey, message: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.sign_message(message);
        ret
    })
}

fn crypto_atomics_key_unlock_and_get_key(it_: &mut CryptoAtomicsKey, password: &str, db_path: &str) -> Result<String, anyhow::Error> {
    craby::catch_panic!({
        let ret = it_.unlock_and_get_key(password, db_path);
        ret
    }).and_then(|r| r)
}


