// Auto generated by Craby. DO NOT EDIT.
// Hash: ae757e2fd36d32ba
#[rustfmt::skip]
use craby::prelude::*;

use crate::ffi::bridging::*;

pub trait CryptoAtomicsKeySpec {
    fn new(ctx: Context) -> Self;
    fn id(&self) -> usize;
    fn generate_and_store(&mut self, password: &str, db_path: &str) -> Void;
    fn get_active_key_hex(&mut self) -> String;
    fn get_derivation_progress(&mut self) -> Number;
    fn set_credentials(&mut self, password: &str, db_path: &str) -> Void;
    fn sign_message(&mut self, message: &str) -> String;
    fn unlock_and_get_key(&mut self, password: &str, db_path: &str) -> Promise<String>;
}
